add new distro archlinux

diff --git a/distro-container-setup b/distro-container-setup
--- a/distro-container-setup
+++ b/distro-container-setup
@@ -5,6 +5,8 @@ function setup_distro() {
     selected_distro="debian"
     elif [[ "$distro_answer" == "2" ]]; then
     selected_distro="ubuntu"
+    elif [[ "$distro_answer" == "3" ]]; then
+    selected_distro="archlinux"
     else
     selected_distro="debian"
     fi
@@ -42,21 +44,85 @@ EOF
 
 function pd_package_install_and_check() {
 	packs_list=($@)
+    if [ -f /etc/os-release ]; then
+    . /etc/os-release
+    fi
 for package_name in "${packs_list[@]}"; do
     echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name ${W}"
+    if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
     sudo apt install "$package_name" -y
+    elif [[ "$ID" == "archlinux" ]]; then
+    sudo pacman -S --noconfirm "$package_name"
+    fi
     if [ $? -ne 0 ]; then
         echo "${R}[${W}-${R}]${G}${BOLD} Error detected during installation of: ${C}$package_name ${W}"
+        if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
         sudo apt --fix-broken install -y
         sudo dpkg --configure -a
         sudo apt install "$package_name" -y
+        elif [[ "$ID" == "archlinux" ]]; then
+        sudo pacman -Syu --noconfirm
+        sudo pacman -S --noconfirm "$package_name"
+        fi
     fi
+    if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
     if dpkg -s "$package_name" >/dev/null 2>&1; then
         echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
     else
         if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
             echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
         fi
+    elif [[ "$ID" == "archlinux" ]]; then
+        if pacman -Qi "$package_name" >/dev/null 2>&1; then
+        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+        else
+        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
+        echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
+        fi
+    fi
+    fi
+done
+echo ""
+}
+
+function pd_root_package_install_and_check() {
+	packs_list=($@)
+    if [ -f /etc/os-release ]; then
+    . /etc/os-release
+    fi
+for package_name in "${packs_list[@]}"; do
+    echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name ${W}"
+    if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
+    apt install "$package_name" -y
+    elif [[ "$ID" == "archlinux" ]]; then
+    pacman -S --noconfirm "$package_name"
+    fi
+    if [ $? -ne 0 ]; then
+        echo "${R}[${W}-${R}]${G}${BOLD} Error detected during installation of: ${C}$package_name ${W}"
+        if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
+        apt --fix-broken install -y
+        dpkg --configure -a
+        apt install "$package_name" -y
+        elif [[ "$ID" == "archlinux" ]]; then
+        pacman -Syu --noconfirm
+        pacman -S --noconfirm "$package_name"
+        fi
+    fi
+    if [[ "$ID" == "debian" ]] || [[ "$ID" == "ubuntu" ]]; then
+    if dpkg -s "$package_name" >/dev/null 2>&1; then
+        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+    else
+        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
+            echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
+        fi
+    elif [[ "$ID" == "archlinux" ]]; then
+        if pacman -Qi "$package_name" >/dev/null 2>&1; then
+        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+        else
+        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
+        echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
+        fi
+    fi
     fi
 done
 echo ""
@@ -85,10 +151,10 @@ W="$(printf '\033[0m')"
 BOLD="$(printf '\033[1m')"
 
 EOF
-declare -f banner package_install_and_check >> $distro_path/root/pd_basic_setup.sh
+declare -f banner pd_root_package_install_and_check >> $distro_path/root/pd_basic_setup.sh
 cat <<EOF >> $distro_path/root/pd_basic_setup.sh
 banner
-package_install_and_check "${distro_packs}"
+pd_root_package_install_and_check "${distro_packs}"
 rm pd_basic_setup.sh
 EOF
 proot-distro login $selected_distro -- /bin/bash -c 'bash pd_basic_setup.sh'
@@ -176,8 +242,10 @@ function distro_terminal_utility_setup() {
 	banner
     echo "${R}[${W}-${R}]${C}${BOLD}Configuring Terminal Utility..."${W}
     echo
+    if [[ "$selected_distro" == "debian" ]] || [[ "$selected_distro" == "debian" ]]; then
 cat <<'EOF' > $distro_path/root/pd_setup.sh
 #!/bin/bash
+
 R="$(printf '\033[1;31m')"                           
 G="$(printf '\033[1;32m')"
 Y="$(printf '\033[1;33m')"
@@ -210,7 +278,7 @@ device_arch=$(uname -m)
     esac
     version=$(get_latest_release "fastfetch-cli" "fastfetch")
     wget -O $distro_path/root/fastfetch.deb https://github.com/fastfetch-cli/fastfetch/releases/download/${version}/fastfetch-linux-${archtype}.deb
-    apt install ./fastfetch.deb
+    apt install ./fastfetch.deb -y
     rm fastfetch.deb
 mkdir -p /etc/apt/keyrings
 wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
@@ -220,17 +288,39 @@ apt update
 apt install -y eza
 rm pd_setup.sh
 EOF
+elif [[ "$selected_distro" == "archlinux" ]]; then
+cat <<'EOF' > $distro_path/root/pd_setup.sh
+#!/bin/bash
+
+R="$(printf '\033[1;31m')"                           
+G="$(printf '\033[1;32m')"
+Y="$(printf '\033[1;33m')"
+B="$(printf '\033[1;34m')"
+C="$(printf '\033[1;36m')"                                       
+W="$(printf '\033[0m')"
+BOLD="$(printf '\033[1m')"
+EOF
+declare -f banner pd_package_install_and_check >> $distro_path/root/pd_setup.sh
+cat <<'EOF' >> $distro_path/root/pd_setup.sh
+pd_package_install_and_check "eza zoxide bat fastfetch"
+EOF
+fi
 proot-distro login $selected_distro -- /bin/bash -c 'bash pd_setup.sh'
 
+if [[ "$selected_distro" == "debian" ]] || [[ "$selected_distro" == "ubuntu" ]]; then
 cat <<'EOF' >> "$save_path/.${pd_shell_name}rc"
 alias apt='sudo nala $@'
 alias apt-get='sudo nala $@'
+EOF
+fi
+
+cat <<'EOF' >> "$save_path/.${pd_shell_name}rc"
 alias cat='bat $@'
 alias ls='eza --icons $@'
 alias mkdir='mkdir -p'
 alias neofetch='fastfetch'
-alias tx11start='echo please run from termux, not inside proot distro.'
-alias tx11stop='echo please run from termux, not inside proot distro.'
+alias tx11start='echo please run it from termux, not inside proot distro.'
+alias tx11stop='echo please run it from termux, not inside proot distro.'
 #######################################################
 # SPECIAL FUNCTIONS
 #######################################################
@@ -322,15 +412,7 @@ EOF
 #################### Create App Installer Shortcut ######################
 #########################################################################
 
-function distro_create_app_installer() {
-    banner
-    echo "${R}[${W}-${R}]${G}${BOLD}Creating App Launcher"${W}
-
-if [[ "$pd_useradd_answer" == "y" ]]; then
-save_user_path="$distro_path/home/$final_user_name"
-fi
-save_root_path="$distro_path/root"
-
+function handel_debian_based_app_installer() {
 cat <<TOP_EOF > "$PREFIX/bin/$selected_distro"
 #!/data/data/com.termux/files/usr/bin/bash
 
@@ -398,6 +480,87 @@ xfce4-panel -r >/dev/null 2>&1
 fi
 
 TOP_EOF
+}
+
+function handel_arch_based_app_installer() {
+cat <<TOP_EOF > "$PREFIX/bin/$selected_distro"
+#!/data/data/com.termux/files/usr/bin/bash
+
+if [[ "\$#" -eq 0 ]]; then
+    proot-distro login --user $final_user_name $selected_distro --shared-tmp
+elif [[ "\$1" = "install" ]]; then
+if [[ ! -d "/data/data/com.termux/files/usr/share/applications/pd_added" ]]; then
+        mkdir -p "/data/data/com.termux/files/usr/share/applications/pd_added"
+        fi
+proot-distro login --user $final_user_name $selected_distro --shared-tmp -- env DISPLAY=:1.0 sudo pacman -S --noconfirm "\${@:2}"
+cat <<EOF > "$save_root_path/packinstall.sh"
+packages=("\${@:2}")
+EOF
+cat <<'EOF' >> "$save_root_path/packinstall.sh"
+for package_name in "\${packages[@]}"; do
+desktop_files=\$(pacman -Ql \$package_name | grep "/usr/share/applications/.*\.desktop$")
+if [ -z "\$desktop_files" ]; then
+    echo "${R}[${W}-${R}]${G} No .desktop files found for package ${C}'\$package_name' ${G}in /usr/share/applications."
+else
+    for desktop_files_name in \$desktop_files; do
+        desktop_files_with_ext=\$(basename "\$desktop_files_name")
+        desktop_files_without_ext="\${desktop_files_with_ext%.desktop}"
+        echo "${R}[${W}-${R}]${G} Adding ${C}\${desktop_files_without_ext} ${G}To Termux Menu"
+        sudo cp "/usr/share/applications/\${desktop_files_with_ext}" "/data/data/com.termux/files/usr/share/applications/pd_added/"
+        sudo sed -i 's/Exec=/Exec=pdrun /g' "/data/data/com.termux/files/usr/share/applications/pd_added/\${desktop_files_with_ext}"
+    done
+fi
+done
+rm packinstall.sh
+EOF
+proot-distro login $selected_distro -- /bin/bash -c 'bash packinstall.sh'
+
+elif [[ "\$1" = "remove" ]]; then
+proot-distro login --user $final_user_name $selected_distro --shared-tmp -- env DISPLAY=:1.0 sudo pacman -R --noconfirm "\${@:2}"
+cat <<EOF > "$save_root_path/packremove.sh"
+packages=("\${@:2}")
+EOF
+cat <<'EOF' >> "$save_root_path/packremove.sh"
+for package_name in "\${packages[@]}"; do
+desktop_files=\$(pacman -Ql \$package_name | grep "/usr/share/applications/.*\.desktop$")
+if [ -z "\$desktop_files" ]; then
+    echo "${R}[${W}-${R}]${G} No .desktop files found for package ${C}'\$package_name' ${G}in /usr/share/applications."
+else
+    for desktop_files_name in \$desktop_files; do
+        desktop_files_with_ext=\$(basename "\$desktop_files_name")
+        desktop_files_without_ext="\${desktop_files_with_ext%.desktop}"
+        echo "${R}[${W}-${R}]${G} Removing ${C}\${desktop_files_without_ext} ${G}From Termux Menu"
+        sudo rm /data/data/com.termux/files/usr/share/applications/pd_added/\${desktop_files_with_ext}
+    done
+fi
+done
+rm packremove.sh
+EOF
+proot-distro login $selected_distro -- /bin/bash -c 'bash packremove.sh'
+else
+echo "sudo pacman -S --noconfirm \$@
+rm else.sh
+" > $save_root_path/else.sh
+proot-distro login $selected_distro -- /bin/sh -c 'bash else.sh'
+fi
+
+TOP_EOF
+}
+
+function distro_create_app_installer() {
+    banner
+    echo "${R}[${W}-${R}]${G}${BOLD}Creating App Launcher"${W}
+
+if [[ "$pd_useradd_answer" == "y" ]]; then
+save_user_path="$distro_path/home/$final_user_name"
+fi
+save_root_path="$distro_path/root"
+
+if [[ "$selected_distro" == "debian" ]] || [[ "$selected_distro" == "ubuntu" ]]; then
+handel_debian_based_app_installer
+elif [[ "$selected_distro" == "archlinux" ]]; then
+handel_arch_based_app_installer
+fi
 
 chmod +x "$PREFIX/bin/$selected_distro"
 
