some fixes and improvement
- add potion to start vncserver and termux x11 without gpu acceleration
- add potion to run distro application without gpu acceleration
- fix vnc setup issue
- fix sudo install issue in distro container
- fix distro package remove issue

diff --git a/distro-container-setup b/distro-container-setup
--- a/distro-container-setup
+++ b/distro-container-setup
@@ -40,17 +40,40 @@ EOF
 ######### Update Distro | Install Required Packages | Add User ##########
 #########################################################################
 
+function pd_package_install_and_check() {
+	packs_list=($@)
+for package_name in "${packs_list[@]}"; do
+    echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name ${W}"
+    sudo apt install "$package_name" -y
+    if [ $? -ne 0 ]; then
+        echo "${R}[${W}-${R}]${G}${BOLD} Error detected during installation of: ${C}$package_name ${W}"
+        sudo apt --fix-broken install -y
+        sudo dpkg --configure -a
+        sudo apt install "$package_name" -y
+    fi
+    if dpkg -s "$package_name" >/dev/null 2>&1; then
+        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+    else
+        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
+            echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
+        fi
+    fi
+done
+echo ""
+}
+
 function distro_basic_task() {
     banner
     echo "${R}[${W}-${R}]${G}${BOLD}Updating ${C}$selected_distro ${G}And Install Required Packages"${W}
     echo
     proot-distro login $selected_distro --shared-tmp -- env DISPLAY=:1.0 apt update
-    if [[ "pd_audio_config_answer" == "n" ]]; then
-    distro_packs="sudo"
-    elif [[ "pd_audio_config_answer" == "y" ]]; then
+    if [[ "$pd_audio_config_answer" == "y" ]]; then
     distro_packs="sudo pulseaudio"
     distro_fix_sound_issue
+    elif [[ "$pd_audio_config_answer" == "n" ]]; then
+    distro_packs="sudo"
     fi
+    echo "pd_audio_config_answer=\"${pd_audio_config_answer}\"" >> $config_file
 cat <<'EOF' > $distro_path/root/pd_basic_setup.sh
 #!/bin/bash
 R="$(printf '\033[1;31m')"                           
@@ -60,11 +83,12 @@ B="$(printf '\033[1;34m')"
 C="$(printf '\033[1;36m')"                                       
 W="$(printf '\033[0m')"
 BOLD="$(printf '\033[1m')"
+
 EOF
 declare -f banner package_install_and_check >> $distro_path/root/pd_basic_setup.sh
 cat <<EOF >> $distro_path/root/pd_basic_setup.sh
 banner
-package_install_and_check "$distro_packs"
+package_install_and_check "${distro_packs}"
 rm pd_basic_setup.sh
 EOF
 proot-distro login $selected_distro -- /bin/bash -c 'bash pd_basic_setup.sh'
@@ -131,33 +155,11 @@ C="$(printf '\033[1;36m')"
 W="$(printf '\033[0m')"
 BOLD="$(printf '\033[1m')"
 
-function package_install_and_check() {
-	packs_list=($@)
-for package_name in "${packs_list[@]}"; do
-    echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name ${W}"
-    sudo apt install "$package_name" -y
-    if [ $? -ne 0 ]; then
-        echo "${R}[${W}-${R}]${G}${BOLD} Error detected during installation of: ${C}$package_name ${W}"
-        sudo apt --fix-broken install -y
-        sudo dpkg --configure -a
-        sudo apt install "$package_name" -y
-    fi
-    if dpkg -s "$package_name" >/dev/null 2>&1; then
-        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
-    else
-        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
-            echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
-        fi
-    fi
-done
-echo ""
-}
-
 EOF
-declare -f banner get_latest_release >> $save_path/pd_zsh_setup.sh
+declare -f banner get_latest_release pd_package_install_and_check >> $save_path/pd_zsh_setup.sh
 cat <<'EOF' >> $save_path/pd_zsh_setup.sh
 banner
-package_install_and_check "git zsh wget"
+pd_package_install_and_check "git zsh wget"
 wget https://raw.githubusercontent.com/sabamdarif/short-linux-scripts/main/install-zsh.sh && bash install-zsh.sh
 rm pd_zsh_setup.sh
 EOF
@@ -183,34 +185,11 @@ B="$(printf '\033[1;34m')"
 C="$(printf '\033[1;36m')"                                       
 W="$(printf '\033[0m')"
 BOLD="$(printf '\033[1m')"
-
-function package_install_and_check() {
-	packs_list=($@)
-for package_name in "${packs_list[@]}"; do
-    echo "${R}[${W}-${R}]${G}${BOLD} Installing package: ${C}$package_name ${W}"
-    sudo apt install "$package_name" -y
-    if [ $? -ne 0 ]; then
-        echo "${R}[${W}-${R}]${G}${BOLD} Error detected during installation of: ${C}$package_name ${W}"
-        sudo apt --fix-broken install -y
-        sudo dpkg --configure -a
-        sudo apt install "$package_name" -y
-    fi
-    if dpkg -s "$package_name" >/dev/null 2>&1; then
-        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
-    else
-        if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
-            echo "${R}[${W}-${R}]${C} $package_name ${G}installed successfully ${W}"
-        fi
-    fi
-done
-echo ""
-}
-
 EOF
-declare -f banner get_latest_release >> $distro_path/root/pd_setup.sh
+declare -f banner get_latest_release pd_package_install_and_check >> $distro_path/root/pd_setup.sh
 cat <<'EOF' >> $distro_path/root/pd_setup.sh
 banner
-package_install_and_check "nala zoxide bat wget gpg"
+pd_package_install_and_check "nala zoxide bat wget gpg"
 device_arch=$(uname -m)
     case "$device_arch" in
         aarch64)
@@ -231,7 +210,7 @@ device_arch=$(uname -m)
     esac
     version=$(get_latest_release "fastfetch-cli" "fastfetch")
     wget -O $distro_path/root/fastfetch.deb https://github.com/fastfetch-cli/fastfetch/releases/download/${version}/fastfetch-linux-${archtype}.deb
-    apt install ./fastfetch.deb -y
+    sudo dpkg -i fastfetch.deb
     rm fastfetch.deb
 mkdir -p /etc/apt/keyrings
 wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
@@ -387,7 +366,7 @@ proot-distro login $selected_distro -- /bin/bash -c 'bash packinstall.sh'
 elif [[ "\$1" = "remove" ]] || [[ "\$1" = "remove" ]]; then
 proot-distro login --user $final_user_name $selected_distro --shared-tmp -- env DISPLAY=:1.0 sudo apt \$1 \${@:2}
 cat <<EOF > "$save_root_path/packremove.sh"
-packages=(${@:2})
+packages=(\${@:2})
 EOF
 cat <<'EOF' >> "$save_root_path/packremove.sh"
 for package_name in "\${packages[@]}"; do
@@ -526,9 +505,21 @@ cp $PREFIX/share/applications/add2menu.desktop $HOME/Desktop/
 function distro_app_launch_setup() {
 cat <<EOF > "$PREFIX/bin/pdrun"
 #!/data/data/com.termux/files/usr/bin/bash
+
 bash ~/.${selected_distro}-sound-access
 xhost +
+case \$1 in
+--no-gpu)
+proot-distro login --user $final_user_name $selected_distro --shared-tmp -- env DISPLAY=:1.0 \$@
+;;
+--help|-h)
+echo "${G}Type ${C}pdrun COMMAND_TO_RUN${G}to start with gpu acceleration"${W}
+echo "${G}Type ${C}pdrun ---no-gpu COMMAND_TO_RUN${G}to start without gpu acceleration"${W}
+*)
+;;
 proot-distro login --user $final_user_name $selected_distro --shared-tmp -- env DISPLAY=:1.0 $selected_pd_hw_method \$@
+;;
+esac
 EOF
 chmod +x "$PREFIX/bin/pdrun"
 }
