improve app installer launcher

diff --git a/setup-termux-desktop b/setup-termux-desktop
--- a/setup-termux-desktop
+++ b/setup-termux-desktop
@@ -41,12 +41,21 @@ function check_and_backup() {
 }
 
 function package_install_and_check() {
-	for package_name in "$@"; do
+	packs_list=($@)
+	for package_name in "${packs_list[@]}"; do
     echo "${R}[${W}-${R}]${G} Installing package: ${C}$package_name${W}"
     pkg install "$package_name" -y
-	
-    if type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
-        echo "${R}[${W}-${R}]${G} $package_name installed successfully${W}"
+	if [ $? -ne 0 ]; then
+    apt --fix-broken install -y
+	dpkg --configure -a
+    fi
+	if dpkg -s "$package_name" >/dev/null 2>&1; then
+    echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+	else
+	if
+    type -p "$package_name" &>/dev/null || [ -e "$PREFIX/bin/$package_name"* ] || [ -e "$PREFIX/bin/"*"$package_name" ]; then
+        echo "${R}[${W}-${R}]${G} $package_name installed successfully ${W}"
+	fi
     fi
 done
 
@@ -62,9 +71,8 @@ function download_and_extract() {
     local url="$1"
     local target_dir="$2"
     local filename="${url##*/}"
-    local filename_no_ext="${filename%.tar.gz}"
 
-    echo "${G}Downloading ${C}${filename_no_ext} ${G}Pack"${W}
+    echo "Downloading ${filename}..."
     sleep 1.5
 
     cd "$target_dir" || return 1
@@ -73,21 +81,44 @@ function download_and_extract() {
     local success=false
 
     while [[ $attempt -le 3 ]]; do
-        if curl -# -L "$url" -o "$filename"; then
-            tar -zxvf "$filename"
-            rm "$filename"
-            success=true
-            break
-        else
-            echo "Failed to download ${filename_no_ext}"
-            echo "Retrying... Attempt $attempt"
-            ((attempt++))
-            sleep 1
+        if [[ $filename == *.tar.gz ]]; then
+            if curl -# -L "$url" -o "$filename"; then
+                tar -zxvf "$filename"
+                rm "$filename"
+                success=true
+                break
+            fi
+        elif [[ $filename == *.tar ]]; then
+            if curl -# -L "$url" -o "$filename"; then
+                tar -xvf "$filename"
+                rm "$filename"
+                success=true
+                break
+            fi
+        elif [[ $filename == *.tar.xz ]]; then
+            if curl -# -L "$url" -o "$filename"; then
+                tar -xvf "$filename"
+                rm "$filename"
+                success=true
+                break
+            fi
+        elif [[ $filename == *.zip ]]; then
+            if curl -# -L "$url" -o "$filename"; then
+                unzip "$filename"
+                rm "$filename"
+                success=true
+                break
+            fi
         fi
+
+        echo "Failed to download ${filename}"
+        echo "Retrying... Attempt $attempt"
+        ((attempt++))
+        sleep 1
     done
 
     if [[ "$success" = false ]]; then
-        echo "Failed to download ${filename_no_ext}"
+        echo "Failed to download ${filename}"
         echo "Please check your internet connection"
     fi
 }
@@ -122,6 +153,12 @@ function confirmation_y_or_n() {
         esac
     done
 
+}
+
+function get_latest_release() {
+  curl -s "https://api.github.com/repos/$1/$2/releases/latest" |
+  grep '"tag_name":' |
+  sed -E 's/.*"([^"]+)".*/\1/'
 }
 
 #########################################################################
@@ -245,11 +282,11 @@ function questions() {
 	echo
 	read -p "${R}[${W}-${R}]${Y}Select Wine Installation Method: "${W} wine_answer
     banner
-	confirmation_y_or_n "Do you want to Configure Zsh" zsh_answer
+	confirmation_y_or_n "Do you want to configure Zsh" zsh_answer
 	banner
 	confirmation_y_or_n "Do you want install some terminal utility to make better terminal exprience" terminal_utility_setup_answer
     banner
-	confirmation_y_or_n "Do you want to Configure termux-x11 ${C}(Rcomended)" tx11_answer
+	confirmation_y_or_n "Do you want to configure termux-x11 ${C}(Rcomended)" tx11_answer
 	banner
 	echo "${R}[${W}-${R}]${Y}Do you want to add a distro container (proot distro)"${W}
 	echo
@@ -305,7 +342,8 @@ function distro_questions() {
 	banner
 	confirmation_y_or_n "Do you want to configure audio support for distro container" pd_audio_config_answer
     banner
-	read -p "${R}[${W}-${R}]${Y}Do you want to create a normal user account ${C}(Recomended) ${Y}(y/n) "${W} useradd_answer
+	confirmation_y_or_n "Do you want to create a normal user account ${C}(Recomended)" useradd_answer
+	echo
     if [[ "$useradd_answer" == "n" ]]; then
     banner
     echo "${R}[${W}-${R}]${G}Skiping User Account Setup"${W}
@@ -317,11 +355,15 @@ function distro_questions() {
     echo
     read -p "${R}[${W}-${R}]${G}Input Password: "${W} pass
     echo
-    read -p "${R}[${W}-${R}]${Y}Do you want to continue with username ${C}$user_name ${Y}and password ${C}$pass${Y} ? (y/n) : " choice
+    read -p "${R}[${W}-${R}]${Y}Do you want to continue with username ${C}$user_name ${Y}and password ${C}$pass${Y} ? (y/n) : "${W} choice
+	echo
 	choice="${choice:-y}"
+	echo
+	echo "${R}[${W}-${R}]${Y}Continuing with answer: $choice"${W}
+	sleep 0.3
     case $choice in
         [yY]* )
-            echo "${R}[${W}-${R}]${G}Continuing with username ${C}$user_name ${G}and password ${C}$pass"
+            echo "${R}[${W}-${R}]${G}Continuing with username ${C}$user_name ${G}and password ${C}$pass"${W}
             break;;
         [nN]* )
              echo "${G}Please provide username and password again."${W}
@@ -343,8 +385,8 @@ function update_sys() {
 	banner
     echo "${R}[${W}-${R}]${G}Updating System...."${W}
 	echo
-    pkg update -y
-    pkg upgrade -y
+    pkg update -y -o Dpkg::Options::="--force-confold"
+	pkg upgrade -y -o Dpkg::Options::="--force-confold"
 }
 
 function install_required_packages() {
@@ -650,9 +692,7 @@ function ide_installer() {
     echo "${R}[${W}-${R}]${G} Installing Vs Code(Code-Oss)..."${W}
 	echo
     sleep 1
-		package_install_and_check "code-oss"
-		echo 'code-oss $@' > $PREFIX/bin/code
-		chmod +x $PREFIX/bin/code
+		package_install_and_check "code-oss code-is-code-oss"
 	elif [[ ${ide_answer} == "2" ]]; then
     echo "${R}[${W}-${R}]${G} installing Geany..."${W}
 	echo
@@ -661,7 +701,7 @@ function ide_installer() {
     echo "${R}[${W}-${R}]${G} Installing Vs Code(Code-Oss)..."${W}
 	echo
     sleep 1
-		package_install_and_check "code-oss"
+		package_install_and_check "code-oss code-is-code-oss"
     echo "${R}[${W}-${R}]${G} installing Geany..."${W}
     echo
 		package_install_and_check "geany"
@@ -673,9 +713,7 @@ function ide_installer() {
     echo "${R}[${W}-${R}]${G} Installing Vs Code(Code-Oss)..."${W}
 	echo
     sleep 1
-		package_install_and_check "code-oss"
-		echo 'code-oss $@' > $PREFIX/bin/code
-		chmod +x $PREFIX/bin/code
+		package_install_and_check "code-oss code-is-code-oss"
 	fi
 }
 
@@ -764,7 +802,7 @@ fi
 }
 
 #########################################################################
-############################## Setup Zsh ################################
+#################### Setup Zsh And Terminal Utility #####################
 #########################################################################
 
 function setup_zsh() {
@@ -785,21 +823,31 @@ fi
 
 function terminal_utility_setup() {
   if [[ "$terminal_utility_setup_answer" == "n" ]];then
+    banner
 	echo "${R}[${W}-${R}]${C}Skipping Terminal Utility Setup..."${W}
 	echo
 	else
-	packs=(nala bat eza)
-	for pack_name in "${packs[@]}"; do
-	package_install_and_check "$pack_name"
-	done
+	banner
+	package_install_and_check "nala bat eza"
 	cat <<'EOF' >> "$HOME/.${shell_name}rc"
 alias apt='nala $@'
 alias pkg='nala $@'
 alias cat='bat $@'
-alias ls='eza -F --icons $@'
+alias ls='eza --icons $@'
 EOF
 termux-reload-settings
 sleep 2
+	fi
+}
+
+#########################################################################
+############################ Install Fonts ##############################
+#########################################################################
+
+function setup_fonts() {
+	if [[ "$terminal_utility_setup_answer" == "y" ]];then
+	echo "${R}[${W}-${R}]${G} Installing Fonts..."${W}
+	package_install_and_check "nerdfix fontconfig-utils"
 	fi
 }
 
@@ -864,6 +912,7 @@ hw_questions
 setup_folder
 setup_zsh
 terminal_utility_setup
+setup_fonts
 install_desktop
 browser_installer
 ide_installer
