separate termux:x11 and vnc
add a separate option to select termux:x11 or vnc or both for gui access

diff --git a/setup-termux-desktop b/setup-termux-desktop
--- a/setup-termux-desktop
+++ b/setup-termux-desktop
@@ -29,18 +29,37 @@ function check_and_create_directory() {
 }
 
 function check_and_delete() {
-	local list=($@)
-	for files in "${list[@]}"; do
-	if [[ -e "$files" ]]; then
-	    rm -rf $files
-    fi
-	done
+	 local list=("$@")
+    for file in "${list[@]}"; do
+        if [[ -e "$file" ]]; then
+            if [[ -d "$file" ]]; then
+                rm -rf "$file"
+            else
+                rm -f "$file"
+            fi
+        fi
+    done
 }
 
 function check_and_backup() {
 	if [[ -e "$1" ]]; then
-		mv "$1" "${1}.bak"
-	fi
+        local backup="${1}.bak"
+        if [[ -e "$backup" ]]; then
+            echo "${G}Backup file ${C}${backup} ${G}already exists."${W}
+            return 1
+        fi
+        mv "$1" "$backup"
+    fi
+}
+
+function check_and_restore() {
+        local backup="${1}.bak"
+        if [[ -e "$backup" ]]; then
+            mv "$backup" "$1"
+		else
+		echo "${G}Backup file ${C}${backup} ${G}does not exists."${W}
+        fi
+        
 }
 
 function package_install_and_check() {
@@ -357,7 +376,16 @@ function questions() {
 	confirmation_y_or_n "Do you want install the terminal utility also for distro container" distro_terminal_utility_setup_answer
 	fi
 	banner
-	confirmation_y_or_n "Do you want to Configuring termux-x11 ${C}(Rcomended)" tx11_answer
+	echo "${R}[${W}-${R}]${G}${BOLD}Select Gui Mode"${W}
+	echo
+	echo "${Y}1. Termux:x11"${W}
+	echo
+	echo "${Y}2. Vnc"${W}
+	echo 
+	echo "${Y}3. Both"${W}
+	echo
+	read -p "${Y}select an option (Default 1): "${W} gui_mode
+	gui_mode=${gui_mode:-1} 
 }
 
 function hw_questions() {
@@ -673,29 +701,16 @@ rm $PREFIX/tmp/.X1-lock > /dev/null 2>&1
 rm $PREFIX/tmp/.X11-unix/X1 > /dev/null 2>&1
 EOF
     chmod +x "$PREFIX/bin/vncstop"
-echo "setup_vnc=\"y\"" >> $config_file
 	
 }
 
-function gui_launcher() {
-    if [[ "$tx11_answer" == "n" ]]; then
-cat << EOF > "$PREFIX/bin/gui"
-#!/data/data/com.termux/files/usr/bin/bash
-
-if [[ "\$1" == "-start" ]]; then
-vncstart
-elif [[ "\$1" == "-stop" ]]; then
-vncstop
-fi
-EOF
-	else
-        banner
+function setup_termux_x11() {
+	banner
         echo "${R}[${W}-${R}]${G}${BOLD} Configuring Termux:X11 "${W}
         echo
         package_install_and_check "termux-x11-nightly"
-
 		sed -i '12s/^#//' $HOME/.termux/termux.properties
-cat <<EOF >> "$PREFIX/bin/tx11start"
+		cat <<EOF >> "$PREFIX/bin/tx11start"
 #!/data/data/com.termux/files/usr/bin/bash
 
 ${initialize_server_method}
@@ -722,25 +737,119 @@ echo "Termux:X11 Stopped Successfully"
 fi
 EOF
 chmod +x $PREFIX/bin/tx11stop
+}
 
-sed -i '12s/^#//' $HOME/.termux/termux.properties
-check_and_delete "$PREFIX/bin/gui"
+function gui_launcher() {
+	check_and_delete "$PREFIX/bin/gui"
+	
+	if [[ "gui_mode" == "1" ]]; then
+	setup_termux_x11
+	echo "selected_gui_mode=\"termux_x11\"" >> $config_file
 cat << EOF > "$PREFIX/bin/gui"
 #!/data/data/com.termux/files/usr/bin/bash
-
-if [[ "\$1" == "-tx11" ]]; then
+case \$1 in
+--start|-l)
 tx11start
-elif [[ "\$1" == "-kill" ]]; then
+;;
+--stop|-s)
 tx11stop
-elif [[ "\$1" == "-start" ]]; then
-vncstart
-elif [[ "\$1" == "-stop" ]]; then
-vncstop
-fi
+;;
+--help|-h)
+echo -e "${G} Use ${C}gui --start / gui -l ${G}to start termux:x11\n Use ${C}gui --stop / gui -s ${G}to stop termux:x11"${W}
+;;
+*)
+echo "${R}Invalid choise"${W}
+gui -h
+;;
+esac
 EOF
-    fi
+	elif [[ "gui_mode" == "2" ]]; then
+	setup_vnc
+	echo "selected_gui_mode=\"vnc\"" >> $config_file
+cat << EOF > "$PREFIX/bin/gui"
+#!/data/data/com.termux/files/usr/bin/bash
+case \$1 in
+--start|-l)
+vncstart
+;;
+--stop|-s)
+vncstop
+;;
+--help|-h)
+echo -e "${G} Use ${C}gui --start / gui -l ${G}to start vnc\n Use ${C}gui --stop / gui -s ${G}to stop vnc"${W}
+;;
+*)
+echo "${R}Invalid choise"${W}
+gui -h
+;;
+esac
+EOF
+	elif [[ "gui_mode" == "3" ]]; then
+	setup_termux_x11
+	setup_vnc
+	echo "selected_gui_mode=\"both\"" >> $config_file
+cat << EOF > "$PREFIX/bin/gui"
+#!/data/data/com.termux/files/usr/bin/bash
+case \$1 in
+    --start|-l)
+        case \$2 in
+            tx11)
+                tx11start
+                ;;
+            vnc)
+                vncstart
+                ;;
+            *)
+                echo -e "${R}Invalid choise. Use ${C}tx11${R} or ${C}vnc ${G}with it${W}"
+                ;;
+        esac
+        ;;
+    --stop|-s)
+        case \$2 in
+            tx11)
+                tx11stop
+                ;;
+            vnc)
+                vncstop
+                ;;
+            *)
+                echo -e "${R}Invalid choise. Use ${C}tx11${R} or ${C}vnc ${G}with it${W}"
+                ;;
+        esac
+        ;;
+    --help|-h)
+        echo -e "${G}Use ${C}gui --start tx11/vnc${G} or ${C}gui -l tx11/vnc${G} to start a gui"
+        echo -e "Use ${C}gui --stop tx11/vnc${G} or ${C}gui -s tx11/vnc${G} to stop a gui${W}"
+        ;;
+    *)
+        echo -e "${R}Invalid choice${W}"
+        gui -h
+        ;;
+esac
+EOF
+	else
+setup_termux_x11
+echo "selected_gui_mode=\"termux_x11\"" >> $config_file
+cat << EOF > "$PREFIX/bin/gui"
+#!/data/data/com.termux/files/usr/bin/bash
+case \$1 in
+--start|-l)
+tx11start
+;;
+--stop|-s)
+tx11stop
+;;
+--help|-h)
+echo -e "${G} Use ${C}gui --start / gui -l ${G}to start termux:x11\n Use ${C}gui --stop / gui -s ${G}to stop termux:x11"${W}
+;;
+*)
+echo "${R}Invalid choise"${W}
+gui -h
+;;
+esac
+EOF
+	fi
 chmod +x "$PREFIX/bin/gui"
-echo "setup_tx11=\"$tx11_answer\"" >> $config_file
 }
 
 #########################################################################
@@ -896,20 +1005,105 @@ function terminal_utility_setup() {
 	banner
 	echo "${R}[${W}-${R}]${C}${BOLD}Configuring Terminal Utility..."${W}
 	echo
-	check_and_backup "$PREFIX/ect/motd"
-	check_and_backup "$PREFIX/ect/motd-playstore"
-	check_and_backup "$PREFIX/ect/motd.sh"
+	check_and_backup "$PREFIX/etc/motd"
+	check_and_backup "$PREFIX/etc/motd-playstore"
+    check_and_backup "$PREFIX/etc/motd.sh"
 	wget -O $PREFIX/etc/motd.sh https://raw.githubusercontent.com/sabamdarif/termux-desktop/main/other/motd.sh
 	echo "bash $PREFIX/etc/motd.sh" > $PREFIX/etc/termux-login.sh
 	check_and_create_directory "$HOME/.termux"
 	check_and_backup "$HOME/.termux/colors.properties"
 	wget -O $HOME/.termux/colors.properties https://raw.githubusercontent.com/sabamdarif/termux-desktop/main/other/colors.properties
-	package_install_and_check "nala bat eza"
+	package_install_and_check "nala bat eza zoxide fastfetch"
 	cat <<'EOF' >> "$HOME/.${shell_name}rc"
 alias apt='nala $@'
 alias pkg='nala $@'
 alias cat='bat $@'
 alias ls='eza --icons $@'
+alias mkdir='mkdir -p'
+alias neofetch='fastfetch'
+#######################################################
+# SPECIAL FUNCTIONS
+#######################################################
+# Extracts any archive(s) (if unp isn't installed)
+extract() {
+	for archive in "$@"; do
+		if [ -f "$archive" ]; then
+			case $archive in
+			*.tar.bz2) tar xvjf $archive ;;
+                        *.tar.xz) tar -xvf $archive ;;
+                        *.tar.gz) tar -xzvf $archive ;;
+			*.tar.gz) tar xvzf $archive ;;
+			*.bz2) bunzip2 $archive ;;
+			*.rar) rar x $archive ;;
+			*.gz) gunzip $archive ;;
+			*.tar) tar xvf $archive ;;
+			*.tbz2) tar xvjf $archive ;;
+			*.tgz) tar xvzf $archive ;;
+			*.zip) unzip $archive ;;
+			*.Z) uncompress $archive ;;
+			*.7z) 7z x $archive ;;
+			*) echo "don't know how to extract '$archive'..." ;;
+			esac
+		else
+			echo "'$archive' is not a valid file!"
+		fi
+	done
+}
+# Searches for text in all files in the current folder
+ftext() {
+	# -i case-insensitive
+	# -I ignore binary files
+	# -H causes filename to be printed
+	# -r recursive search
+	# -n causes line number to be printed
+	# optional: -F treat search term as a literal, not a regular expression
+	# optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
+	grep -iIHrn --color=always "$1" . | less -r
+}
+# Copy file with a progress bar
+cpp() {
+	set -e
+	strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
+		awk '{
+	count += $NF
+	if (count % 10 == 0) {
+		percent = count / total_size * 100
+		printf "%3d%% [", percent
+		for (i=0;i<=percent;i++)
+			printf "="
+			printf ">"
+			for (i=percent;i<100;i++)
+				printf " "
+				printf "]\r"
+			}
+		}
+	END { print "" }' total_size="$(stat -c '%s' "${1}")" count=0
+}
+# Copy and go to the directory
+cpg() {
+	if [ -d "$2" ]; then
+		cp "$1" "$2" && cd "$2"
+	else
+		cp "$1" "$2"
+	fi
+}
+# Move and go to the directory
+mvg() {
+	if [ -d "$2" ]; then
+		mv "$1" "$2" && cd "$2"
+	else
+		mv "$1" "$2"
+	fi
+}
+# Create and go to the directory
+mkdirg() {
+	mkdir -p "$1"
+	cd "$1"
+}
+EOF
+cat <<EOF >> "$HOME/.${shell_name}rc"
+#set zoxide as cd
+eval "\$(zoxide init --cmd cd ${shell_name})"
 EOF
 termux-reload-settings
 sleep 2
@@ -1017,6 +1211,9 @@ function remove_termux_desktop() {
 	fi
 	#remove terminal utility
 	if [[ "$terminal_utility_setup" == "y" ]];then
+	check_and_restore "$PREFIX/etc/motd"
+	check_and_restore "$PREFIX/etc/motd-playstore"
+	check_and_restore "$PREFIX/etc/motd.sh"
 	check_and_delete "$PREFIX/etc/motd.sh $PREFIX/etc/termux-login.sh $HOME/.termux $HOME/.fonts/font.ttf"
 	package_check_and_remove "nerdfix fontconfig-utils nala bat eza"
 	fi
@@ -1090,12 +1287,16 @@ function remove_termux_desktop() {
 	package_check_and_remove "proot-distro"
 	fi
 	#remove vnc and termux x11
-	if [[ "$setup_vnc" == "y" ]];then
+	check_and_delete "$PREFIX/bin/gui"
+	if [[ "$selected_gui_mode" == "termux_x11" ]];then
+	package_check_and_remove "termux-x11-nightly"
+	check_and_delete "$PREFIX/bin/tx11start $PREFIX/bin/tx11stop"
+	elif [[ "$selected_gui_mode" == "vnc" ]];then
 	package_check_and_remove "tigervnc xorg-xhost"
 	check_and_delete "$HOME/.vnc/xstartup $PREFIX/bin/vncstart $PREFIX/bin/vncstop $PREFIX/bin/gui $PREFIX/bin/tx11start $PREFIX/bin/tx11stop"
-	fi
-	if [[ "$setup_tx11" == "y" ]];then
-	package_check_and_remove "termux-x11-nightly"
+	elif [[ "$selected_gui_mode" == "both" ]];then
+	package_check_and_remove "termux-x11-nightly tigervnc xorg-xhost"
+	check_and_delete "$PREFIX/bin/tx11start $PREFIX/bin/tx11stop $HOME/.vnc/xstartup $PREFIX/bin/vncstart $PREFIX/bin/vncstop $PREFIX/bin/gui $PREFIX/bin/tx11start $PREFIX/bin/tx11stop"
 	fi
 	check_and_delete "$PREFIX/etc/termux-desktop"
 	fi
@@ -1133,7 +1334,6 @@ setup_config
 fi
 hw_config
 distro_container_setup
-setup_vnc
 gui_launcher
 terminal_utility_setup
 add_theme_change_option
